### ISSUE TITLE
Applying Provisioning template - SingleOrDefault error when the template has a List

### ISSUE THREAD

**Issue by AntyfrizZz** [SharePoint/PnP-Provisioning-Schema#323]
Hello there,

I have an issue when i am trying to apply a provisioning template to a subsite. The current issue occurs when the site has List in it.
My Steps:
1. Creating brand new subsite (manualy)
2. Adding List to it (manualy)
3. Extract the template
ProvisioningTemplateCreationInformation ptci = new ProvisioningTemplateCreationInformation(ctx.Web)
{
    FileConnector = new FileSystemConnector(TemplatePath, string.Empty),
    PersistBrandingFiles = true,
    PersistPublishingFiles = true,
    ProgressDelegate = (string message, int progress, int total) =>
    {
        Console.WriteLine($"{progress:00}/{total:00} - {message}");
    }
};
ProvisioningTemplate template = ctx.Web.GetProvisioningTemplate(ptci);

4. Create new subsite
WebCreationInformation wci = new WebCreationInformation
{
    Description = "test descr",
    Title = title,
    Url = title.Replace(" ", string.Empty).ToLower(),
    UseSamePermissionsAsParentSite = true
};
ctx.Web.Webs.Add(wci);
5. Apply the template to it
ProvisioningTemplateApplyingInformation ptai = new ProvisioningTemplateApplyingInformation
{
    ProgressDelegate = (string message, int progress, int total) =>
    {
        Console.WriteLine("{0:00}/{1:00} - {2}", progress, total, message);
    }
};

FileSystemConnector connector = new FileSystemConnector(TemplatePath, string.Empty);
template.Connector = connector;
ctx.Web.ApplyProvisioningTemplate(template, ptai);

The error:
Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at lambda_method(Closure )
   at System.Linq.EnumerableExecutor`1.Execute()
   at System.Linq.EnumerableQuery`1.System.Linq.IQueryProvider.Execute[S](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at lambda_method(Closure )
   at Microsoft.SharePoint.Client.ClientQueryProvider.ExecuteExpression[TResult](Expression expression)
   at Microsoft.SharePoint.Client.ClientQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateList(Web web, ListInstance templateList, TokenParser parser, PnPMonitoredScope scope, Boolean isNoScriptSite)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)

Thank you in advance,
Yavor

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
