### ISSUE TITLE
Apply-PnPProvisioningTemplate : List 'User Information List' does not exist at site with URL

### ISSUE THREAD

**Issue by rheid** [SharePoint/PnP-Provisioning-Schema#343]
Hello everyone, 

today I get a new error in the Apply-PnPProvisioningTemplate function that "User Information List" does not exist. I same xml template runs last week without any problem. Inside the xml template there is no reference to that list. Anyone got any idea where this might come from?

**Comment by rheid** [comment]
The same error happened if I create a new template without any modification:

powershell.exe Information: 0 : 2018-10-22 18:40:13.0000        [List instances]        [10]    [Debug] Updating list Documents failed: List 'User Information List' does not exist at site with URL 'https://icthdt.sharepoint.com/sites/rheidtempl001'. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenDefinitions.ListIdToken.GetReplaceValue()
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser.BuildTokenCache()
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser.ParseString(String input, String[] tokensToSkip)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.UpdateList(Web web, List existingList, ListInstance templateList, TokenParser parser, PnPMonitoredScope scope, Boolean isNoScriptSite)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)      8371ms  ee8f4df9-532d-493b-b3e6-5c2bbe3b40cc
powershell.exe Information: 0 : 2018-10-22 18:40:13.0060        [List instances]        [10]    [Debug] Code execution scope ended      8377ms  ee8f4df9-532d-493b-b3e6-5c2bbe3b40cc
powershell.exe Information: 0 : 2018-10-22 18:40:13.0060        [Provisioning]  [10]    [Debug] Code execution scope ended      24225ms ee8f4df9-532d-493b-b3e6-5c2bbe3b40cc
Apply-PnPProvisioningTemplate : List 'User Information List' does not exist at site with URL
'https://icthdt.sharepoint.com/sites/rheidtempl001'.
At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path $templateFile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate
